### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by kkostadinov99** [kkostadinov99/covid-19-recovery-identification#3]
A short proposal for further development of the project "Building a Critical Infrastructure for the Nation-Wide Identification of Recovered COVID-19 Patients".

- [ ] Add more ways for users to share information that is shared through the use of QR codes at the moment. One suggestion is the implementation of URI Schemes.

- [ ] Fix Libsodium dependency. As of now, the service uses a manually-built version of Libsodium and it is difficult to update or replace it.

- [ ] Split the GUI and the service in two. This would allow for the service to become a npm package and anyone who needs to use the service for something other than immunity certificates can just create a new GUI. Also, it would be easier to support Android and iOS versions with just one codebase for the GUI.

- [ ]  Rewrite partially the GUI (React Native code), in order to make the code testable. The problem is that there is not enough documentation about testing code that uses the React Native framework and is written in TypeScript. A possible solution is to rewrite the codebase from TypeScript to JavaScript.

- [ ] Test the codebase more thoroughly. This should be accomplished through integration and system tests. Tools like Jest should be used.

- [ ] Write a proper CI/CD for Jenkins (used by the Tribler organisation). Add support for running the test suite against a variety of emulated devices.

- [ ]  Add iOS support. It should be implemented similarly to the Android version as iOS supports foreground services.
